# Generated by Django 3.2.16 on 2022-11-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_coin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernft',
            name='nft_deployed_contract_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernft',
            name='nft_deployed_contract_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
