# Generated by Django 3.2.16 on 2022-11-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator_coin', '0003_alter_usernfttransactionhistory_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbetaemails',
            name='creator_obj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator_coin.creatorprofile'),
        ),
    ]
